services:
  transcendence:
    container_name: transcendence
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    volumes:
      - data:/app

volumes:
  data:
    driver: local
