volumes:
  database-data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "4242:3000"
    networks:
      - backend
    environment:
      - DATABASE_URL=${DATABASE_HOST}
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - backend
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
