volumes:
  transcendence_vol:

services:
  transcendence:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # - GOOGLE_OAUTH_CLIENT_ID=
      # - GOOGLE_OAUTH_CLIENT_SECRET=
      # - JWT_SECRET=
      # - HOST_URI=
    env_file:
      - .env
    volumes:
      - transcendence_vol:/app/db
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

