name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies for API
      run: npm ci
      working-directory: ./api
    - name: Install dependencies for App
      run: npm ci
      working-directory: ./app
    - name: Build API
      run: npm run build
      working-directory: ./api
    - name: Build App
      run: npm run build
      working-directory: ./app
    - name: Test API
      run: npm test
      working-directory: ./api
    - name: Test App
      run: npm test
      working-directory: ./app